if("dplyr" %in% rownames(installed.packages()) == FALSE) {
  install.packages("dplyr")
}
library(dplyr)

#3 - convertActivityCodeToName()
# DESCRIPTION: Uses descriptive activity names to name the activities in the data set
# INPUT: activityCode - integer value from 1 to 6
# OUTPUT: returns corresponding Activity Code name
convertActivityCodeToName <- function(activityCode) {
  activityMap <- c('WALKING', 'WALKING_UPSTAIRS',
                    'WALKING_DOWNSTAIRS', 'SITTING',
                    'STANDING', 'LAYING')
  
  activityMap[activityCode]
}

#1 - mergeDatasets()  
# DESCRIPTION: Merges the training and the test sets to create one data set.
# INPUT: dir - the directory for "UCI HAR Dataset"
# OUTPUT: returns a uciHarDataFrame (a data.frame of the merged data for test and train. 
#         See code book for more details.)
# EXAMPLE: mergeDatasets('UCI HAR Dataset')
mergeDatasets <- function(dir) {
  #4 Appropriately labels the data set with descriptive variable names.   
  cnames <- list(c('subject'), 
                 c('tBodyAcc.mean.X.1',
                   'tBodyAcc.mean.Y.2',
                   'tBodyAcc.mean.Z.3',
                   'tBodyAcc.std.X.4',
                   'tBodyAcc.std.Y.5',
                   'tBodyAcc.std.Z.6',
                   'tBodyAcc.mad.X.7',
                   'tBodyAcc.mad.Y.8',
                   'tBodyAcc.mad.Z.9',
                   'tBodyAcc.max.X.10',
                   'tBodyAcc.max.Y.11',
                   'tBodyAcc.max.Z.12',
                   'tBodyAcc.min.X.13',
                   'tBodyAcc.min.Y.14',
                   'tBodyAcc.min.Z.15',
                   'tBodyAcc.sma.16',
                   'tBodyAcc.energy.X.17',
                   'tBodyAcc.energy.Y.18',
                   'tBodyAcc.energy.Z.19',
                   'tBodyAcc.iqr.X.20',
                   'tBodyAcc.iqr.Y.21',
                   'tBodyAcc.iqr.Z.22',
                   'tBodyAcc.entropy.X.23',
                   'tBodyAcc.entropy.Y.24',
                   'tBodyAcc.entropy.Z.25',
                   'tBodyAcc.arCoeff.X.1.26',
                   'tBodyAcc.arCoeff.X.2.27',
                   'tBodyAcc.arCoeff.X.3.28',
                   'tBodyAcc.arCoeff.X.4.29',
                   'tBodyAcc.arCoeff.Y.1.30',
                   'tBodyAcc.arCoeff.Y.2.31',
                   'tBodyAcc.arCoeff.Y.3.32',
                   'tBodyAcc.arCoeff.Y.4.33',
                   'tBodyAcc.arCoeff.Z.1.34',
                   'tBodyAcc.arCoeff.Z.2.35',
                   'tBodyAcc.arCoeff.Z.3.36',
                   'tBodyAcc.arCoeff.Z.4.37',
                   'tBodyAcc.correlation.X.Y.38',
                   'tBodyAcc.correlation.X.Z.39',
                   'tBodyAcc.correlation.Y.Z.40',
                   'tGravityAcc.mean.X.41',
                   'tGravityAcc.mean.Y.42',
                   'tGravityAcc.mean.Z.43',
                   'tGravityAcc.std.X.44',
                   'tGravityAcc.std.Y.45',
                   'tGravityAcc.std.Z.46',
                   'tGravityAcc.mad.X.47',
                   'tGravityAcc.mad.Y.48',
                   'tGravityAcc.mad.Z.49',
                   'tGravityAcc.max.X.50',
                   'tGravityAcc.max.Y.51',
                   'tGravityAcc.max.Z.52',
                   'tGravityAcc.min.X.53',
                   'tGravityAcc.min.Y.54',
                   'tGravityAcc.min.Z.55',
                   'tGravityAcc.sma.56',
                   'tGravityAcc.energy.X.57',
                   'tGravityAcc.energy.Y.58',
                   'tGravityAcc.energy.Z.59',
                   'tGravityAcc.iqr.X.60',
                   'tGravityAcc.iqr.Y.61',
                   'tGravityAcc.iqr.Z.62',
                   'tGravityAcc.entropy.X.63',
                   'tGravityAcc.entropy.Y.64',
                   'tGravityAcc.entropy.Z.65',
                   'tGravityAcc.arCoeff.X.1.66',
                   'tGravityAcc.arCoeff.X.2.67',
                   'tGravityAcc.arCoeff.X.3.68',
                   'tGravityAcc.arCoeff.X.4.69',
                   'tGravityAcc.arCoeff.Y.1.70',
                   'tGravityAcc.arCoeff.Y.2.71',
                   'tGravityAcc.arCoeff.Y.3.72',
                   'tGravityAcc.arCoeff.Y.4.73',
                   'tGravityAcc.arCoeff.Z.1.74',
                   'tGravityAcc.arCoeff.Z.2.75',
                   'tGravityAcc.arCoeff.Z.3.76',
                   'tGravityAcc.arCoeff.Z.4.77',
                   'tGravityAcc.correlation.X.Y.78',
                   'tGravityAcc.correlation.X.Z.79',
                   'tGravityAcc.correlation.Y.Z.80',
                   'tBodyAccJerk.mean.X.81',
                   'tBodyAccJerk.mean.Y.82',
                   'tBodyAccJerk.mean.Z.83',
                   'tBodyAccJerk.std.X.84',
                   'tBodyAccJerk.std.Y.85',
                   'tBodyAccJerk.std.Z.86',
                   'tBodyAccJerk.mad.X.87',
                   'tBodyAccJerk.mad.Y.88',
                   'tBodyAccJerk.mad.Z.89',
                   'tBodyAccJerk.max.X.90',
                   'tBodyAccJerk.max.Y.91',
                   'tBodyAccJerk.max.Z.92',
                   'tBodyAccJerk.min.X.93',
                   'tBodyAccJerk.min.Y.94',
                   'tBodyAccJerk.min.Z.95',
                   'tBodyAccJerk.sma.96',
                   'tBodyAccJerk.energy.X.97',
                   'tBodyAccJerk.energy.Y.98',
                   'tBodyAccJerk.energy.Z.99',
                   'tBodyAccJerk.iqr.X.100',
                   'tBodyAccJerk.iqr.Y.101',
                   'tBodyAccJerk.iqr.Z.102',
                   'tBodyAccJerk.entropy.X.103',
                   'tBodyAccJerk.entropy.Y.104',
                   'tBodyAccJerk.entropy.Z.105',
                   'tBodyAccJerk.arCoeff.X.1.106',
                   'tBodyAccJerk.arCoeff.X.2.107',
                   'tBodyAccJerk.arCoeff.X.3.108',
                   'tBodyAccJerk.arCoeff.X.4.109',
                   'tBodyAccJerk.arCoeff.Y.1.110',
                   'tBodyAccJerk.arCoeff.Y.2.111',
                   'tBodyAccJerk.arCoeff.Y.3.112',
                   'tBodyAccJerk.arCoeff.Y.4.113',
                   'tBodyAccJerk.arCoeff.Z.1.114',
                   'tBodyAccJerk.arCoeff.Z.2.115',
                   'tBodyAccJerk.arCoeff.Z.3.116',
                   'tBodyAccJerk.arCoeff.Z.4.117',
                   'tBodyAccJerk.correlation.X.Y.118',
                   'tBodyAccJerk.correlation.X.Z.119',
                   'tBodyAccJerk.correlation.Y.Z.120',
                   'tBodyGyro.mean.X.121',
                   'tBodyGyro.mean.Y.122',
                   'tBodyGyro.mean.Z.123',
                   'tBodyGyro.std.X.124',
                   'tBodyGyro.std.Y.125',
                   'tBodyGyro.std.Z.126',
                   'tBodyGyro.mad.X.127',
                   'tBodyGyro.mad.Y.128',
                   'tBodyGyro.mad.Z.129',
                   'tBodyGyro.max.X.130',
                   'tBodyGyro.max.Y.131',
                   'tBodyGyro.max.Z.132',
                   'tBodyGyro.min.X.133',
                   'tBodyGyro.min.Y.134',
                   'tBodyGyro.min.Z.135',
                   'tBodyGyro.sma.136',
                   'tBodyGyro.energy.X.137',
                   'tBodyGyro.energy.Y.138',
                   'tBodyGyro.energy.Z.139',
                   'tBodyGyro.iqr.X.140',
                   'tBodyGyro.iqr.Y.141',
                   'tBodyGyro.iqr.Z.142',
                   'tBodyGyro.entropy.X.143',
                   'tBodyGyro.entropy.Y.144',
                   'tBodyGyro.entropy.Z.145',
                   'tBodyGyro.arCoeff.X.1.146',
                   'tBodyGyro.arCoeff.X.2.147',
                   'tBodyGyro.arCoeff.X.3.148',
                   'tBodyGyro.arCoeff.X.4.149',
                   'tBodyGyro.arCoeff.Y.1.150',
                   'tBodyGyro.arCoeff.Y.2.151',
                   'tBodyGyro.arCoeff.Y.3.152',
                   'tBodyGyro.arCoeff.Y.4.153',
                   'tBodyGyro.arCoeff.Z.1.154',
                   'tBodyGyro.arCoeff.Z.2.155',
                   'tBodyGyro.arCoeff.Z.3.156',
                   'tBodyGyro.arCoeff.Z.4.157',
                   'tBodyGyro.correlation.X.Y.158',
                   'tBodyGyro.correlation.X.Z.159',
                   'tBodyGyro.correlation.Y.Z.160',
                   'tBodyGyroJerk.mean.X.161',
                   'tBodyGyroJerk.mean.Y.162',
                   'tBodyGyroJerk.mean.Z.163',
                   'tBodyGyroJerk.std.X.164',
                   'tBodyGyroJerk.std.Y.165',
                   'tBodyGyroJerk.std.Z.166',
                   'tBodyGyroJerk.mad.X.167',
                   'tBodyGyroJerk.mad.Y.168',
                   'tBodyGyroJerk.mad.Z.169',
                   'tBodyGyroJerk.max.X.170',
                   'tBodyGyroJerk.max.Y.171',
                   'tBodyGyroJerk.max.Z.172',
                   'tBodyGyroJerk.min.X.173',
                   'tBodyGyroJerk.min.Y.174',
                   'tBodyGyroJerk.min.Z.175',
                   'tBodyGyroJerk.sma.176',
                   'tBodyGyroJerk.energy.X.177',
                   'tBodyGyroJerk.energy.Y.178',
                   'tBodyGyroJerk.energy.Z.179',
                   'tBodyGyroJerk.iqr.X.180',
                   'tBodyGyroJerk.iqr.Y.181',
                   'tBodyGyroJerk.iqr.Z.182',
                   'tBodyGyroJerk.entropy.X.183',
                   'tBodyGyroJerk.entropy.Y.184',
                   'tBodyGyroJerk.entropy.Z.185',
                   'tBodyGyroJerk.arCoeff.X.1.186',
                   'tBodyGyroJerk.arCoeff.X.2.187',
                   'tBodyGyroJerk.arCoeff.X.3.188',
                   'tBodyGyroJerk.arCoeff.X.4.189',
                   'tBodyGyroJerk.arCoeff.Y.1.190',
                   'tBodyGyroJerk.arCoeff.Y.2.191',
                   'tBodyGyroJerk.arCoeff.Y.3.192',
                   'tBodyGyroJerk.arCoeff.Y.4.193',
                   'tBodyGyroJerk.arCoeff.Z.1.194',
                   'tBodyGyroJerk.arCoeff.Z.2.195',
                   'tBodyGyroJerk.arCoeff.Z.3.196',
                   'tBodyGyroJerk.arCoeff.Z.4.197',
                   'tBodyGyroJerk.correlation.X.Y.198',
                   'tBodyGyroJerk.correlation.X.Z.199',
                   'tBodyGyroJerk.correlation.Y.Z.200',
                   'tBodyAccMag.mean.201',
                   'tBodyAccMag.std.202',
                   'tBodyAccMag.mad.203',
                   'tBodyAccMag.max.204',
                   'tBodyAccMag.min.205',
                   'tBodyAccMag.sma.206',
                   'tBodyAccMag.energy.207',
                   'tBodyAccMag.iqr.208',
                   'tBodyAccMag.entropy.209',
                   'tBodyAccMag.arCoeff1.210',
                   'tBodyAccMag.arCoeff2.211',
                   'tBodyAccMag.arCoeff3.212',
                   'tBodyAccMag.arCoeff4.213',
                   'tGravityAccMag.mean.214',
                   'tGravityAccMag.std.215',
                   'tGravityAccMag.mad.216',
                   'tGravityAccMag.max.217',
                   'tGravityAccMag.min.218',
                   'tGravityAccMag.sma.219',
                   'tGravityAccMag.energy.220',
                   'tGravityAccMag.iqr.221',
                   'tGravityAccMag.entropy.222',
                   'tGravityAccMag.arCoeff1.223',
                   'tGravityAccMag.arCoeff2.224',
                   'tGravityAccMag.arCoeff3.225',
                   'tGravityAccMag.arCoeff4.226',
                   'tBodyAccJerkMag.mean.227',
                   'tBodyAccJerkMag.std.228',
                   'tBodyAccJerkMag.mad.229',
                   'tBodyAccJerkMag.max.230',
                   'tBodyAccJerkMag.min.231',
                   'tBodyAccJerkMag.sma.232',
                   'tBodyAccJerkMag.energy.233',
                   'tBodyAccJerkMag.iqr.234',
                   'tBodyAccJerkMag.entropy.235',
                   'tBodyAccJerkMag.arCoeff1.236',
                   'tBodyAccJerkMag.arCoeff2.237',
                   'tBodyAccJerkMag.arCoeff3.238',
                   'tBodyAccJerkMag.arCoeff4.239',
                   'tBodyGyroMag.mean.240',
                   'tBodyGyroMag.std.241',
                   'tBodyGyroMag.mad.242',
                   'tBodyGyroMag.max.243',
                   'tBodyGyroMag.min.244',
                   'tBodyGyroMag.sma.245',
                   'tBodyGyroMag.energy.246',
                   'tBodyGyroMag.iqr.247',
                   'tBodyGyroMag.entropy.248',
                   'tBodyGyroMag.arCoeff1.249',
                   'tBodyGyroMag.arCoeff2.250',
                   'tBodyGyroMag.arCoeff3.251',
                   'tBodyGyroMag.arCoeff4.252',
                   'tBodyGyroJerkMag.mean.253',
                   'tBodyGyroJerkMag.std.254',
                   'tBodyGyroJerkMag.mad.255',
                   'tBodyGyroJerkMag.max.256',
                   'tBodyGyroJerkMag.min.257',
                   'tBodyGyroJerkMag.sma.258',
                   'tBodyGyroJerkMag.energy.259',
                   'tBodyGyroJerkMag.iqr.260',
                   'tBodyGyroJerkMag.entropy.261',
                   'tBodyGyroJerkMag.arCoeff1.262',
                   'tBodyGyroJerkMag.arCoeff2.263',
                   'tBodyGyroJerkMag.arCoeff3.264',
                   'tBodyGyroJerkMag.arCoeff4.265',
                   'fBodyAcc.mean.X.266',
                   'fBodyAcc.mean.Y.267',
                   'fBodyAcc.mean.Z.268',
                   'fBodyAcc.std.X.269',
                   'fBodyAcc.std.Y.270',
                   'fBodyAcc.std.Z.271',
                   'fBodyAcc.mad.X.272',
                   'fBodyAcc.mad.Y.273',
                   'fBodyAcc.mad.Z.274',
                   'fBodyAcc.max.X.275',
                   'fBodyAcc.max.Y.276',
                   'fBodyAcc.max.Z.277',
                   'fBodyAcc.min.X.278',
                   'fBodyAcc.min.Y.279',
                   'fBodyAcc.min.Z.280',
                   'fBodyAcc.sma.281',
                   'fBodyAcc.energy.X.282',
                   'fBodyAcc.energy.Y.283',
                   'fBodyAcc.energy.Z.284',
                   'fBodyAcc.iqr.X.285',
                   'fBodyAcc.iqr.Y.286',
                   'fBodyAcc.iqr.Z.287',
                   'fBodyAcc.entropy.X.288',
                   'fBodyAcc.entropy.Y.289',
                   'fBodyAcc.entropy.Z.290',
                   'fBodyAcc.maxInds.X.291',
                   'fBodyAcc.maxInds.Y.292',
                   'fBodyAcc.maxInds.Z.293',
                   'fBodyAcc.meanFreq.X.294',
                   'fBodyAcc.meanFreq.Y.295',
                   'fBodyAcc.meanFreq.Z.296',
                   'fBodyAcc.skewness.X.297',
                   'fBodyAcc.kurtosis.X.298',
                   'fBodyAcc.skewness.Y.299',
                   'fBodyAcc.kurtosis.Y.300',
                   'fBodyAcc.skewness.Z.301',
                   'fBodyAcc.kurtosis.Z.302',
                   'fBodyAcc.bandsEnergy.1.8.303',
                   'fBodyAcc.bandsEnergy.9.16.304',
                   'fBodyAcc.bandsEnergy.17.24.305',
                   'fBodyAcc.bandsEnergy.25.32.306',
                   'fBodyAcc.bandsEnergy.33.40.307',
                   'fBodyAcc.bandsEnergy.41.48.308',
                   'fBodyAcc.bandsEnergy.49.56.309',
                   'fBodyAcc.bandsEnergy.57.64.310',
                   'fBodyAcc.bandsEnergy.1.16.311',
                   'fBodyAcc.bandsEnergy.17.32.312',
                   'fBodyAcc.bandsEnergy.33.48.313',
                   'fBodyAcc.bandsEnergy.49.64.314',
                   'fBodyAcc.bandsEnergy.1.24.315',
                   'fBodyAcc.bandsEnergy.25.48.316',
                   'fBodyAcc.bandsEnergy.1.8.317',
                   'fBodyAcc.bandsEnergy.9.16.318',
                   'fBodyAcc.bandsEnergy.17.24.319',
                   'fBodyAcc.bandsEnergy.25.32.320',
                   'fBodyAcc.bandsEnergy.33.40.321',
                   'fBodyAcc.bandsEnergy.41.48.322',
                   'fBodyAcc.bandsEnergy.49.56.323',
                   'fBodyAcc.bandsEnergy.57.64.324',
                   'fBodyAcc.bandsEnergy.1.16.325',
                   'fBodyAcc.bandsEnergy.17.32.326',
                   'fBodyAcc.bandsEnergy.33.48.327',
                   'fBodyAcc.bandsEnergy.49.64.328',
                   'fBodyAcc.bandsEnergy.1.24.329',
                   'fBodyAcc.bandsEnergy.25.48.330',
                   'fBodyAcc.bandsEnergy.1.8.331',
                   'fBodyAcc.bandsEnergy.9.16.332',
                   'fBodyAcc.bandsEnergy.17.24.333',
                   'fBodyAcc.bandsEnergy.25.32.334',
                   'fBodyAcc.bandsEnergy.33.40.335',
                   'fBodyAcc.bandsEnergy.41.48.336',
                   'fBodyAcc.bandsEnergy.49.56.337',
                   'fBodyAcc.bandsEnergy.57.64.338',
                   'fBodyAcc.bandsEnergy.1.16.339',
                   'fBodyAcc.bandsEnergy.17.32.340',
                   'fBodyAcc.bandsEnergy.33.48.341',
                   'fBodyAcc.bandsEnergy.49.64.342',
                   'fBodyAcc.bandsEnergy.1.24.343',
                   'fBodyAcc.bandsEnergy.25.48.344',
                   'fBodyAccJerk.mean.X.345',
                   'fBodyAccJerk.mean.Y.346',
                   'fBodyAccJerk.mean.Z.347',
                   'fBodyAccJerk.std.X.348',
                   'fBodyAccJerk.std.Y.349',
                   'fBodyAccJerk.std.Z.350',
                   'fBodyAccJerk.mad.X.351',
                   'fBodyAccJerk.mad.Y.352',
                   'fBodyAccJerk.mad.Z.353',
                   'fBodyAccJerk.max.X.354',
                   'fBodyAccJerk.max.Y.355',
                   'fBodyAccJerk.max.Z.356',
                   'fBodyAccJerk.min.X.357',
                   'fBodyAccJerk.min.Y.358',
                   'fBodyAccJerk.min.Z.359',
                   'fBodyAccJerk.sma.360',
                   'fBodyAccJerk.energy.X.361',
                   'fBodyAccJerk.energy.Y.362',
                   'fBodyAccJerk.energy.Z.363',
                   'fBodyAccJerk.iqr.X.364',
                   'fBodyAccJerk.iqr.Y.365',
                   'fBodyAccJerk.iqr.Z.366',
                   'fBodyAccJerk.entropy.X.367',
                   'fBodyAccJerk.entropy.Y.368',
                   'fBodyAccJerk.entropy.Z.369',
                   'fBodyAccJerk.maxInds.X.370',
                   'fBodyAccJerk.maxInds.Y.371',
                   'fBodyAccJerk.maxInds.Z.372',
                   'fBodyAccJerk.meanFreq.X.373',
                   'fBodyAccJerk.meanFreq.Y.374',
                   'fBodyAccJerk.meanFreq.Z.375',
                   'fBodyAccJerk.skewness.X.376',
                   'fBodyAccJerk.kurtosis.X.377',
                   'fBodyAccJerk.skewness.Y.378',
                   'fBodyAccJerk.kurtosis.Y.379',
                   'fBodyAccJerk.skewness.Z.380',
                   'fBodyAccJerk.kurtosis.Z.381',
                   'fBodyAccJerk.bandsEnergy.1.8.382',
                   'fBodyAccJerk.bandsEnergy.9.16.383',
                   'fBodyAccJerk.bandsEnergy.17.24.384',
                   'fBodyAccJerk.bandsEnergy.25.32.385',
                   'fBodyAccJerk.bandsEnergy.33.40.386',
                   'fBodyAccJerk.bandsEnergy.41.48.387',
                   'fBodyAccJerk.bandsEnergy.49.56.388',
                   'fBodyAccJerk.bandsEnergy.57.64.389',
                   'fBodyAccJerk.bandsEnergy.1.16.390',
                   'fBodyAccJerk.bandsEnergy.17.32.391',
                   'fBodyAccJerk.bandsEnergy.33.48.392',
                   'fBodyAccJerk.bandsEnergy.49.64.393',
                   'fBodyAccJerk.bandsEnergy.1.24.394',
                   'fBodyAccJerk.bandsEnergy.25.48.395',
                   'fBodyAccJerk.bandsEnergy.1.8.396',
                   'fBodyAccJerk.bandsEnergy.9.16.397',
                   'fBodyAccJerk.bandsEnergy.17.24.398',
                   'fBodyAccJerk.bandsEnergy.25.32.399',
                   'fBodyAccJerk.bandsEnergy.33.40.400',
                   'fBodyAccJerk.bandsEnergy.41.48.401',
                   'fBodyAccJerk.bandsEnergy.49.56.402',
                   'fBodyAccJerk.bandsEnergy.57.64.403',
                   'fBodyAccJerk.bandsEnergy.1.16.404',
                   'fBodyAccJerk.bandsEnergy.17.32.405',
                   'fBodyAccJerk.bandsEnergy.33.48.406',
                   'fBodyAccJerk.bandsEnergy.49.64.407',
                   'fBodyAccJerk.bandsEnergy.1.24.408',
                   'fBodyAccJerk.bandsEnergy.25.48.409',
                   'fBodyAccJerk.bandsEnergy.1.8.410',
                   'fBodyAccJerk.bandsEnergy.9.16.411',
                   'fBodyAccJerk.bandsEnergy.17.24.412',
                   'fBodyAccJerk.bandsEnergy.25.32.413',
                   'fBodyAccJerk.bandsEnergy.33.40.414',
                   'fBodyAccJerk.bandsEnergy.41.48.415',
                   'fBodyAccJerk.bandsEnergy.49.56.416',
                   'fBodyAccJerk.bandsEnergy.57.64.417',
                   'fBodyAccJerk.bandsEnergy.1.16.418',
                   'fBodyAccJerk.bandsEnergy.17.32.419',
                   'fBodyAccJerk.bandsEnergy.33.48.420',
                   'fBodyAccJerk.bandsEnergy.49.64.421',
                   'fBodyAccJerk.bandsEnergy.1.24.422',
                   'fBodyAccJerk.bandsEnergy.25.48.423',
                   'fBodyGyro.mean.X.424',
                   'fBodyGyro.mean.Y.425',
                   'fBodyGyro.mean.Z.426',
                   'fBodyGyro.std.X.427',
                   'fBodyGyro.std.Y.428',
                   'fBodyGyro.std.Z.429',
                   'fBodyGyro.mad.X.430',
                   'fBodyGyro.mad.Y.431',
                   'fBodyGyro.mad.Z.432',
                   'fBodyGyro.max.X.433',
                   'fBodyGyro.max.Y.434',
                   'fBodyGyro.max.Z.435',
                   'fBodyGyro.min.X.436',
                   'fBodyGyro.min.Y.437',
                   'fBodyGyro.min.Z.438',
                   'fBodyGyro.sma.439',
                   'fBodyGyro.energy.X.440',
                   'fBodyGyro.energy.Y.441',
                   'fBodyGyro.energy.Z.442',
                   'fBodyGyro.iqr.X.443',
                   'fBodyGyro.iqr.Y.444',
                   'fBodyGyro.iqr.Z.445',
                   'fBodyGyro.entropy.X.446',
                   'fBodyGyro.entropy.Y.447',
                   'fBodyGyro.entropy.Z.448',
                   'fBodyGyro.maxInds.X.449',
                   'fBodyGyro.maxInds.Y.450',
                   'fBodyGyro.maxInds.Z.451',
                   'fBodyGyro.meanFreq.X.452',
                   'fBodyGyro.meanFreq.Y.453',
                   'fBodyGyro.meanFreq.Z.454',
                   'fBodyGyro.skewness.X.455',
                   'fBodyGyro.kurtosis.X.456',
                   'fBodyGyro.skewness.Y.457',
                   'fBodyGyro.kurtosis.Y.458',
                   'fBodyGyro.skewness.Z.459',
                   'fBodyGyro.kurtosis.Z.460',
                   'fBodyGyro.bandsEnergy.1.8.461',
                   'fBodyGyro.bandsEnergy.9.16.462',
                   'fBodyGyro.bandsEnergy.17.24.463',
                   'fBodyGyro.bandsEnergy.25.32.464',
                   'fBodyGyro.bandsEnergy.33.40.465',
                   'fBodyGyro.bandsEnergy.41.48.466',
                   'fBodyGyro.bandsEnergy.49.56.467',
                   'fBodyGyro.bandsEnergy.57.64.468',
                   'fBodyGyro.bandsEnergy.1.16.469',
                   'fBodyGyro.bandsEnergy.17.32.470',
                   'fBodyGyro.bandsEnergy.33.48.471',
                   'fBodyGyro.bandsEnergy.49.64.472',
                   'fBodyGyro.bandsEnergy.1.24.473',
                   'fBodyGyro.bandsEnergy.25.48.474',
                   'fBodyGyro.bandsEnergy.1.8.475',
                   'fBodyGyro.bandsEnergy.9.16.476',
                   'fBodyGyro.bandsEnergy.17.24.477',
                   'fBodyGyro.bandsEnergy.25.32.478',
                   'fBodyGyro.bandsEnergy.33.40.479',
                   'fBodyGyro.bandsEnergy.41.48.480',
                   'fBodyGyro.bandsEnergy.49.56.481',
                   'fBodyGyro.bandsEnergy.57.64.482',
                   'fBodyGyro.bandsEnergy.1.16.483',
                   'fBodyGyro.bandsEnergy.17.32.484',
                   'fBodyGyro.bandsEnergy.33.48.485',
                   'fBodyGyro.bandsEnergy.49.64.486',
                   'fBodyGyro.bandsEnergy.1.24.487',
                   'fBodyGyro.bandsEnergy.25.48.488',
                   'fBodyGyro.bandsEnergy.1.8.489',
                   'fBodyGyro.bandsEnergy.9.16.490',
                   'fBodyGyro.bandsEnergy.17.24.491',
                   'fBodyGyro.bandsEnergy.25.32.492',
                   'fBodyGyro.bandsEnergy.33.40.493',
                   'fBodyGyro.bandsEnergy.41.48.494',
                   'fBodyGyro.bandsEnergy.49.56.495',
                   'fBodyGyro.bandsEnergy.57.64.496',
                   'fBodyGyro.bandsEnergy.1.16.497',
                   'fBodyGyro.bandsEnergy.17.32.498',
                   'fBodyGyro.bandsEnergy.33.48.499',
                   'fBodyGyro.bandsEnergy.49.64.500',
                   'fBodyGyro.bandsEnergy.1.24.501',
                   'fBodyGyro.bandsEnergy.25.48.502',
                   'fBodyAccMag.mean.503',
                   'fBodyAccMag.std.504',
                   'fBodyAccMag.mad.505',
                   'fBodyAccMag.max.506',
                   'fBodyAccMag.min.507',
                   'fBodyAccMag.sma.508',
                   'fBodyAccMag.energy.509',
                   'fBodyAccMag.iqr.510',
                   'fBodyAccMag.entropy.511',
                   'fBodyAccMag.maxInds.512',
                   'fBodyAccMag.meanFreq.513',
                   'fBodyAccMag.skewness.514',
                   'fBodyAccMag.kurtosis.515',
                   'fBodyBodyAccJerkMag.mean.516',
                   'fBodyBodyAccJerkMag.std.517',
                   'fBodyBodyAccJerkMag.mad.518',
                   'fBodyBodyAccJerkMag.max.519',
                   'fBodyBodyAccJerkMag.min.520',
                   'fBodyBodyAccJerkMag.sma.521',
                   'fBodyBodyAccJerkMag.energy.522',
                   'fBodyBodyAccJerkMag.iqr.523',
                   'fBodyBodyAccJerkMag.entropy.524',
                   'fBodyBodyAccJerkMag.maxInds.525',
                   'fBodyBodyAccJerkMag.meanFreq.526',
                   'fBodyBodyAccJerkMag.skewness.527',
                   'fBodyBodyAccJerkMag.kurtosis.528',
                   'fBodyBodyGyroMag.mean.529',
                   'fBodyBodyGyroMag.std.530',
                   'fBodyBodyGyroMag.mad.531',
                   'fBodyBodyGyroMag.max.532',
                   'fBodyBodyGyroMag.min.533',
                   'fBodyBodyGyroMag.sma.534',
                   'fBodyBodyGyroMag.energy.535',
                   'fBodyBodyGyroMag.iqr.536',
                   'fBodyBodyGyroMag.entropy.537',
                   'fBodyBodyGyroMag.maxInds.538',
                   'fBodyBodyGyroMag.meanFreq.539',
                   'fBodyBodyGyroMag.skewness.540',
                   'fBodyBodyGyroMag.kurtosis.541',
                   'fBodyBodyGyroJerkMag.mean.542',
                   'fBodyBodyGyroJerkMag.std.543',
                   'fBodyBodyGyroJerkMag.mad.544',
                   'fBodyBodyGyroJerkMag.max.545',
                   'fBodyBodyGyroJerkMag.min.546',
                   'fBodyBodyGyroJerkMag.sma.547',
                   'fBodyBodyGyroJerkMag.energy.548',
                   'fBodyBodyGyroJerkMag.iqr.549',
                   'fBodyBodyGyroJerkMag.entropy.550',
                   'fBodyBodyGyroJerkMag.maxInds.551',
                   'fBodyBodyGyroJerkMag.meanFreq.552',
                   'fBodyBodyGyroJerkMag.skewness.553',
                   'fBodyBodyGyroJerkMag.kurtosis.554',
                   'angle.tBodyAccMean.gravity.555',
                   'angle.tBodyAccJerkMean.gravityMean.556',
                   'angle.tBodyGyroMean.gravityMean.557',
                   'angle.tBodyGyroJerkMean.gravityMean.558',
                   'angle.X.gravityMean.559',
                   'angle.Y.gravityMean.560',
                   'angle.Z.gravityMean.561'), 
                  c('activity'))
  testFilenames <- c("test/subject_test.txt", "test/X_test.txt", "test/y_test.txt")
  trainFilenames <- c("train/subject_train.txt", "train/X_train.txt", "train/y_train.txt")
  
  uciHarDataFrame <- NULL

  for(i in 1:length(testFilenames)) {
    testFilename <- testFilenames[i]
    trainFilename <- trainFilenames[i]
      
    #currData1 <- read.table(file=paste('.', dir, testFilename, sep='/'))
    #currData2 <- read.table(file=paste('.', dir, trainFilename, sep='/'))
    currData1 <- read.table(file=paste(dir, testFilename, sep='/'))
    currData2 <- read.table(file=paste(dir, trainFilename, sep='/'))    
    currData <- rbind(currData1, currData2)
    
    if (i == 3) {
      currData <- data.frame(apply(currData, 1, convertActivityCodeToName))
    }
    
    currColNames <- cnames[[i]]
    
    if (is.null(uciHarDataFrame)) {
      colnames(currData) <- currColNames
      uciHarDataFrame <- currData
    } else {
      colnames(currData) <- currColNames
      uciHarDataFrame <- cbind(uciHarDataFrame, currData, deparse.level = 0)
    }
  }
  
  uciHarDataFrame
}

#2a - getUciHarMean()
# DESCRIPTION: Extracts only the measurements on the mean for each measurement. 
# INPUT: uciHarDataFrame - the output of mergeDatasets()  
# OUTPUT: returns a vector with the mean for each numeric columns in uciHarDataFrame
getUciHarMean <- function(uciHarDataFrame) {
  allColNames <- names(uciHarDataFrame)
  c <- allColNames[allColNames != 'subject' & allColNames != 'activity'] 
  m <- apply(uciHarDataFrame[,c], 2, mean)
}

# 2b - getUciHarSd()
# DESCRIPTION: Extracts only the measurements on the standard deviation for each measurement. 
# INPUT: uciHarDataFrame - the output of mergeDatasets()  
# OUTPUT: returns a vector with the standard deviation for each numeric columns in uciHarDataFrame
getUciHarSd <- function(uciHarDataFrame) {
  allColNames <- names(uciHarDataFrame)
  c <- allColNames[allColNames != 'subject' & allColNames != 'activity'] 
  bar <- apply(uciHarDataFrame[,c], 2, sd)
}

#5 - getTidyUciHarMeanByActivitySubject()
# DESCRIPTION: From the data set in step 4, creates a second, independent tidy data set with the average 
#              of each variable for each activity and each subject.
# INPUT: uciHarDataFrame - the output of mergeDatasets()  
# OUTPUT: returns a new data.frame with the mean of each numeric value by Activity and Subject
getTidyUciHarMeanByActivitySubject <- function(uciHarDataFrame) {
  g <- uciHarDataFrame %>% group_by(activity, subject)
  allColNames <- names(uciHarDataFrame)
  c <- allColNames[allColNames != 'subject' & allColNames != 'activity']  
  g %>% summarise_each_(funs(mean), c)
}
  

#uciHarDataFrame <- mergeDatasets('UCI HAR Dataset')
#uciHarMean <- getUciHarMean(uciHarDataFrame)
#uciHarSd <- getUciHarSd(uciHarDataFrame)
#tidyUciHarMeanByActivitySubject <- getTidyUciHarMeanByActivitySubject(uciHarDataFrame)